export const ACCOUNT_ATTR_QUERY = `SELECT 
                                        customer.id, 
                                        customer.descriptive_name, 
                                        customer.manager, 
                                        customer.currency_code, 
                                        customer.time_zone,
                                        customer.status, 
                                        customer.call_reporting_setting.call_reporting_enabled, 
                                        customer.call_reporting_setting.call_conversion_reporting_enabled, 
                                        customer.conversion_tracking_setting.conversion_tracking_id, 
                                        customer.conversion_tracking_setting.conversion_tracking_status, 
                                        customer.remarketing_setting.google_global_site_tag, 
                                        customer.optimization_score 
                                        FROM customer`;

export const CAMPAIGN_ATTR_QUERY = `SELECT 
                                        campaign.id, 
                                        campaign.name,
                                        campaign.resource_name, 
                                        campaign.campaign_budget,
                                        campaign.status, 
                                        campaign.advertising_channel_type,
                                        campaign.manual_cpc.enhanced_cpc_enabled,
                                        campaign.maximize_conversion_value.target_roas, 
                                        campaign.maximize_conversions.target_cpa_micros, 
                                        campaign.network_settings.target_content_network, 
                                        campaign.network_settings.target_google_search, 
                                        campaign.network_settings.target_partner_search_network, 
                                        campaign.network_settings.target_search_network, 
                                        campaign.network_settings.target_youtube, 
                                        campaign.percent_cpc.cpc_bid_ceiling_micros, 
                                        campaign.percent_cpc.enhanced_cpc_enabled, 
                                        campaign.optimization_score, 
                                        campaign.start_date, 
                                        campaign.end_date
                                        FROM campaign`;

export const ADGROUP_ATTR_QUERY = `SELECT
                                        campaign.id,
                                        ad_group.id,
                                        ad_group.name,
                                        ad_group.cpc_bid_micros,
                                        ad_group.cpm_bid_micros,
                                        ad_group.cpv_bid_micros,
                                        ad_group.status,
                                        ad_group.target_cpa_micros,
                                        ad_group.target_cpm_micros,
                                        ad_group.target_cpv_micros,
                                        ad_group.target_roas,
                                        ad_group.type,
                                        ad_group.resource_name
                                        FROM ad_group`;

export const AD_ATTR_QUERY = `SELECT 
                                        campaign.id,
                                        ad_group.id,
                                        ad_group_ad.ad.id, 
                                        ad_group_ad.ad.name,
                                        ad_group_ad.status, 
                                        ad_group_ad.ad.type, 
                                        ad_group_ad.ad.call_ad.business_name, 
                                        ad_group_ad.ad.call_ad.call_tracked, 
                                        ad_group_ad.ad.call_ad.conversion_action, 
                                        ad_group_ad.ad.call_ad.conversion_reporting_state, 
                                        ad_group_ad.ad.call_ad.country_code, 
                                        ad_group_ad.ad.call_ad.description1, 
                                        ad_group_ad.ad.call_ad.description2, 
                                        ad_group_ad.ad.call_ad.disable_call_conversion, 
                                        ad_group_ad.ad.call_ad.headline1, 
                                        ad_group_ad.ad.call_ad.headline2, 
                                        ad_group_ad.ad.call_ad.path1, 
                                        ad_group_ad.ad.call_ad.path2, 
                                        ad_group_ad.ad.call_ad.phone_number, 
                                        ad_group_ad.ad.call_ad.phone_number_verification_url, 
                                        ad_group_ad.ad.device_preference, 
                                        ad_group_ad.ad.display_url, 
                                        ad_group_ad.ad.expanded_dynamic_search_ad.description, 
                                        ad_group_ad.ad.expanded_dynamic_search_ad.description2, 
                                        ad_group_ad.ad.expanded_text_ad.description, 
                                        ad_group_ad.ad.expanded_text_ad.description2, 
                                        ad_group_ad.ad.expanded_text_ad.headline_part1, 
                                        ad_group_ad.ad.expanded_text_ad.headline_part2, 
                                        ad_group_ad.ad.expanded_text_ad.headline_part3, 
                                        ad_group_ad.ad.expanded_text_ad.path1, 
                                        ad_group_ad.ad.expanded_text_ad.path2, 
                                        ad_group_ad.ad.final_mobile_urls, 
                                        ad_group_ad.ad.final_urls, 
                                        ad_group_ad.ad.image_ad.image_asset.asset, 
                                        ad_group_ad.ad.image_ad.image_url, 
                                        ad_group_ad.ad.image_ad.mime_type, 
                                        ad_group_ad.ad.image_ad.name, 
                                        ad_group_ad.ad.image_ad.pixel_height, 
                                        ad_group_ad.ad.image_ad.pixel_width, 
                                        ad_group_ad.ad.image_ad.preview_image_url, 
                                        ad_group_ad.ad.image_ad.preview_pixel_height, 
                                        ad_group_ad.ad.image_ad.preview_pixel_width, 
                                        ad_group_ad.ad.responsive_display_ad.accent_color, 
                                        ad_group_ad.ad.responsive_display_ad.allow_flexible_color, 
                                        ad_group_ad.ad.responsive_display_ad.call_to_action_text, 
                                        ad_group_ad.ad.responsive_display_ad.business_name, 
                                        ad_group_ad.ad.responsive_display_ad.control_spec.enable_asset_enhancements, 
                                        ad_group_ad.ad.responsive_display_ad.control_spec.enable_autogen_video, 
                                        ad_group_ad.ad.responsive_display_ad.descriptions, 
                                        ad_group_ad.ad.responsive_display_ad.format_setting, 
                                        ad_group_ad.ad.responsive_display_ad.headlines, 
                                        ad_group_ad.ad.responsive_display_ad.logo_images, 
                                        ad_group_ad.ad.responsive_display_ad.long_headline, 
                                        ad_group_ad.ad.responsive_display_ad.main_color, 
                                        ad_group_ad.ad.responsive_display_ad.marketing_images, 
                                        ad_group_ad.ad.responsive_display_ad.price_prefix, 
                                        ad_group_ad.ad.responsive_display_ad.promo_text, 
                                        ad_group_ad.ad.responsive_display_ad.square_logo_images, 
                                        ad_group_ad.ad.responsive_display_ad.square_marketing_images, 
                                        ad_group_ad.ad.responsive_display_ad.youtube_videos, 
                                        ad_group_ad.ad.responsive_search_ad.descriptions, 
                                        ad_group_ad.ad.responsive_search_ad.headlines, 
                                        ad_group_ad.ad.responsive_search_ad.path1, 
                                        ad_group_ad.ad.responsive_search_ad.path2, 
                                        ad_group_ad.ad.smart_campaign_ad.descriptions, 
                                        ad_group_ad.ad.smart_campaign_ad.headlines, 
                                        ad_group_ad.ad.text_ad.description1, 
                                        ad_group_ad.ad.text_ad.description2, 
                                        ad_group_ad.ad.text_ad.headline, 
                                        ad_group_ad.ad.video_ad.bumper.action_button_label, 
                                        ad_group_ad.ad.video_ad.bumper.action_headline, 
                                        ad_group_ad.ad.video_ad.bumper.companion_banner.asset, 
                                        ad_group_ad.ad.video_ad.in_feed.description1, 
                                        ad_group_ad.ad.video_ad.in_feed.description2, 
                                        ad_group_ad.ad.video_ad.in_feed.headline, 
                                        ad_group_ad.ad.video_ad.in_feed.thumbnail, 
                                        ad_group_ad.ad.video_ad.in_stream.action_button_label, 
                                        ad_group_ad.ad.video_ad.in_stream.action_headline, 
                                        ad_group_ad.ad.video_ad.in_stream.companion_banner.asset, 
                                        ad_group_ad.ad.video_ad.non_skippable.action_button_label, 
                                        ad_group_ad.ad.video_ad.non_skippable.action_headline, 
                                        ad_group_ad.ad.video_ad.non_skippable.companion_banner.asset, 
                                        ad_group_ad.ad.video_ad.out_stream.description, 
                                        ad_group_ad.ad.video_ad.out_stream.headline, 
                                        ad_group_ad.ad.video_ad.video.asset, 
                                        ad_group_ad.ad.video_responsive_ad.breadcrumb1, 
                                        ad_group_ad.ad.video_responsive_ad.breadcrumb2, 
                                        ad_group_ad.ad.video_responsive_ad.call_to_actions, 
                                        ad_group_ad.ad.video_responsive_ad.companion_banners, 
                                        ad_group_ad.ad.video_responsive_ad.descriptions, 
                                        ad_group_ad.ad.video_responsive_ad.headlines, 
                                        ad_group_ad.ad.video_responsive_ad.long_headlines, 
                                        ad_group_ad.ad.video_responsive_ad.videos 
                                        FROM ad_group_ad`;

export const KEYWORD_ATTR_QUERY = `SELECT 
                                        campaign.id,
                                        ad_group.id,
                                        ad_group_criterion.criterion_id,
                                        ad_group_criterion.type, 
                                        ad_group_criterion.status, 
                                        ad_group_criterion.bid_modifier, 
                                        ad_group_criterion.cpc_bid_micros, 
                                        ad_group_criterion.keyword.text, 
                                        ad_group_criterion.keyword.match_type
                                        FROM ad_group_criterion`;

export const IS_MANAGER_QUERY = `SELECT 
                                    customer.descriptive_name,
                                    customer.manager 
                                    FROM customer 
                                    WHERE 
                                    customer.id = `;

export const CUSTOMER_DETAILS_QUERY = `
                                 SELECT 
                                    customer_client.client_customer, 
                                    customer_client.manager, 
                                    customer_client.descriptive_name
                                    FROM customer_client
                                    WHERE customer_client.level = 1`;

export const CAMPAIGN_METRICS_QUERY = `SELECT
                                    segments.date,
                                    campaign.id,
                                    metrics.clicks,
                                    metrics.impressions,
                                    metrics.ctr,
                                    metrics.interactions,
                                    metrics.interaction_rate,
                                    metrics.average_cpc,
                                    metrics.average_cpe,
                                    metrics.average_cpm,
                                    metrics.average_cpv,
                                    metrics.average_cost,
                                    metrics.all_conversions,
                                    metrics.all_conversions_value,
                                    metrics.cost_per_all_conversions,
                                    metrics.value_per_all_conversions,
                                    metrics.cost_micros,
                                    metrics.revenue_micros,
                                    metrics.view_through_conversions,
                                    metrics.video_quartile_p100_rate, 
                                    metrics.video_quartile_p25_rate, 
                                    metrics.video_quartile_p50_rate, 
                                    metrics.video_quartile_p75_rate, 
                                    metrics.video_view_rate, 
                                    metrics.video_views,
                                    metrics.phone_calls,
                                    metrics.phone_impressions,
                                    metrics.phone_through_rate,
                                    metrics.invalid_clicks,
                                    metrics.invalid_click_rate,
                                    metrics.search_absolute_top_impression_share,
                                    metrics.search_budget_lost_absolute_top_impression_share,
                                    metrics.search_budget_lost_impression_share,
                                    metrics.search_budget_lost_top_impression_share,
                                    metrics.search_click_share,
                                    metrics.search_exact_match_impression_share,
                                    metrics.search_impression_share,
                                    metrics.search_rank_lost_absolute_top_impression_share,
                                    metrics.search_rank_lost_impression_share,
                                    metrics.search_rank_lost_top_impression_share,
                                    metrics.search_top_impression_share
                                    FROM campaign`;

export const ADGROUP_METRICS_QUERY = `SELECT 
                                    segments.date, 
                                    campaign.id, 
                                    ad_group.id,
                                    metrics.clicks, 
                                    metrics.impressions, 
                                    metrics.ctr, 
                                    metrics.interactions, 
                                    metrics.interaction_rate, 
                                    metrics.average_cpc, 
                                    metrics.average_cpe, 
                                    metrics.average_cpm, 
                                    metrics.average_cpv, 
                                    metrics.average_cost, 
                                    metrics.all_conversions, 
                                    metrics.all_conversions_value, 
                                    metrics.cost_micros, 
                                    metrics.revenue_micros, 
                                    metrics.view_through_conversions,
                                    metrics.video_quartile_p100_rate, 
                                    metrics.video_quartile_p25_rate, 
                                    metrics.video_quartile_p50_rate, 
                                    metrics.video_quartile_p75_rate, 
                                    metrics.video_view_rate, 
                                    metrics.video_views, 
                                    metrics.phone_calls,
                                    metrics.phone_impressions,
                                    metrics.phone_through_rate,
                                    metrics.search_absolute_top_impression_share, 
                                    metrics.search_budget_lost_absolute_top_impression_share, 
                                    metrics.search_budget_lost_top_impression_share, 
                                    metrics.search_exact_match_impression_share, 
                                    metrics.search_impression_share, 
                                    metrics.search_rank_lost_absolute_top_impression_share, 
                                    metrics.search_rank_lost_impression_share, 
                                    metrics.search_rank_lost_top_impression_share, 
                                    metrics.search_top_impression_share
                                    FROM ad_group `;

export const AD_METRICS_QUERY = `SELECT 
                                    segments.date, 
                                    campaign.id, 
                                    ad_group.id, 
                                    ad_group_ad.ad.id,
                                    metrics.clicks, 
                                    metrics.impressions, 
                                    metrics.ctr, 
                                    metrics.interactions, 
                                    metrics.interaction_rate, 
                                    metrics.average_cpc, 
                                    metrics.average_cpe, 
                                    metrics.average_cpm, 
                                    metrics.average_cpv, 
                                    metrics.average_cost, 
                                    metrics.all_conversions, 
                                    metrics.all_conversions_value, 
                                    metrics.cost_micros, 
                                    metrics.revenue_micros, 
                                    metrics.view_through_conversions, 
                                    metrics.video_quartile_p100_rate, 
                                    metrics.video_quartile_p25_rate, 
                                    metrics.video_quartile_p50_rate, 
                                    metrics.video_quartile_p75_rate, 
                                    metrics.video_view_rate, 
                                    metrics.video_views 
                                    FROM ad_group_ad`;

export const KEYWORD_METRICS_QUERY = `SELECT 
                                    segments.date, 
                                    campaign.id, 
                                    ad_group.id, 
                                    ad_group_criterion.criterion_id, 
                                    metrics.clicks, 
                                    metrics.impressions, 
                                    metrics.ctr, 
                                    metrics.interactions, 
                                    metrics.interaction_rate, 
                                    metrics.average_cpc, 
                                    metrics.average_cpe, 
                                    metrics.average_cpm, 
                                    metrics.average_cpv, 
                                    metrics.average_cost, 
                                    metrics.all_conversions, 
                                    metrics.all_conversions_value, 
                                    metrics.cost_micros, 
                                    metrics.revenue_micros, 
                                    metrics.view_through_conversions,
                                    metrics.video_quartile_p100_rate, 
                                    metrics.video_quartile_p25_rate, 
                                    metrics.video_quartile_p50_rate, 
                                    metrics.video_quartile_p75_rate, 
                                    metrics.video_view_rate, 
                                    metrics.video_views, 
                                    metrics.search_absolute_top_impression_share, 
                                    metrics.search_budget_lost_absolute_top_impression_share, 
                                    metrics.search_budget_lost_top_impression_share, 
                                    metrics.search_click_share, 
                                    metrics.search_exact_match_impression_share, 
                                    metrics.search_impression_share, 
                                    metrics.search_rank_lost_absolute_top_impression_share, 
                                    metrics.search_rank_lost_impression_share, 
                                    metrics.search_rank_lost_top_impression_share, 
                                    metrics.search_top_impression_share
                                    FROM keyword_view`;
